# Generated by Django 5.1.6 on 2025-03-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(blank=True, max_length=255)),
                ('column2', models.CharField(blank=True, max_length=255)),
                ('column3', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
