# Generated by Django 5.1.6 on 2025-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='column1',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='exceldata',
            old_name='column2',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='column3',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
    ]
